blank_issues_enabled: false
contact_links:
  - name: 質問・相談
    url: https://ichmy.0t0.jp/blog/?page_id=830
    about: バグ報告や機能リクエスト以外の質問・相談はichmyのサイトの掲示板をご利用ください。

# Issue作成時のテンプレート設定
defaults:
  - template: "bug_report.yml"
    name: ":bug:バグ報告"
    about: "バグを報告する"
  - template: "feature_request.yml"
    name: ":eight_spoked_asterisk:機能リクエスト"
    about: "新機能のアイデアを提案する"
